### ISSUE TITLE
Package subpath "./package.json" error

### ISSUE THREAD

**Issue by brechtvdv** [LinkedSoftwareDependencies/Components-Generator.js#95]
When upgrading componentsjs-generator from 2.6.0 to 3.0.0 and using @solid/community-server (3.0.0), following error is returned when building:
> componentsjs-generator -s src -c dist/components -i .componentsignore -r knows-scs

>Package subpath './package.json' is not defined by "exports" in C:\Users\Administrator\Documents\solid-calendar-store\node_modules\ws\package.json

**Comment by rubensworks** [comment]
This is due to the new "exports" syntax in package.json.
See https://github.com/RubenVerborgh/AsyncIterator/pull/34 for more details.
Nothing about this can be done here unfortunately.

But I guess you probably don't want to update to the new generator yet, since CSS is not using it yet AFAIK.

**Comment by joachimvh** [comment]
@rubensworks What would be the reason I don't see this error when upgrading the components.js dependencies in CSS to the latest version? Because `ws` is a dependency coming from CSS. That branch is still on the previous version of Comunica though if that's related.

**Comment by rubensworks** [comment]
Perhaps it's being ignored somehow? Or just not used by CSS, but only in @brechtvdv's project?
CJS will only require those dependencies that are actively being used by a specific config.

**Comment by joachimvh** [comment]
The class that has the `ws` dependency is being imported in the default configs, so it is definitely being used.

**Comment by rubensworks** [comment]
`ws` added support for ESM since version 8, which caused their `exports` entry in package.json to change (and broke Node.js's `require.resolve`). But I see CSS is using 8.4.2, so versioning is also not the problem.

**Comment by joachimvh** [comment]
Is this error thrown by the type checking system? Just realized that that is probably going to be the difference since CSS disables the strict type checking for other issues.

**Comment by rubensworks** [comment]
This issue was created in the generator repo, so that's before type-checking even.

**Comment by joachimvh** [comment]
Looking into this since it affects all external components of the community server now 5.0.0 is released so this needs to be fixed before any external component can be upgraded.

@rubensworks I know where it is happening but want some feedback first on what best to do about it. I'll dump all the information I found here.

The error happens here specifically: https://github.com/LinkedSoftwareDependencies/Components-Generator.js/blob/823deb987b50efadaa0e22fb2ea7e637a7ea37ae/lib/resolution/ExternalModulesLoader.ts#L204

A very easy fix (which I tested and seems to work), is to wrap that call in a try/catch and then filter out the packages that failed, perhaps with a logger warning. So if that's fine I would make a PR for that.

The reason this doesn't happen in CSS is because that function doesn't get called at all there. In CSS `buildModuleStateSelective` gets an empty array as input, which I think is because none of its classes depend on an external components.js project for their configuration (is my guess). My hello world component gets `[ '@solid/community-server' ]` as input though. Probably because it creates a new component that extends a class from that package. This eventually causes `ws` to end up in the resolve call above.

There are other resolve calls in the code though, those all happen in `ResolutionContext.resolvePackageIndex`. In the case of the CSS `ws` gets resolved there, specifically here:
https://github.com/LinkedSoftwareDependencies/Components-Generator.js/blob/823deb987b50efadaa0e22fb2ea7e637a7ea37ae/lib/resolution/ResolutionContext.ts#L111-L112

So in this case `@types/ws` gets checked first, which does not have the `package.json` issue and no error gets thrown.

Question is now if the `ExternalModulesLoader` call above also needs to do first check for a type package or if there is a reason this is different? Although adding that check there might fix it, I don't think that fully covers the problem of faulty packages breaking the entire generator. In case `ws` had its typings in the package itself CSS would probably also have crashed on this. So I think the most robust solution would be something that makes sure such a package can't break the entire build, but that would probably require a bigger refactor.

**Comment by rubensworks** [comment]
Sure, try-catching it with a warning and skipping sounds good!

> Question is now if the ExternalModulesLoader call above also needs to do first check for a type package or if there is a reason this is different?

That sounds like a (potential) bug indeed.
